modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
	modId="aamod"
	version="0.0.1"
	displayName="Action-Adventure Mod"
	authors="Jack Gagnon, William Steele"
	description='''
An Action-Adventure Mod Inspired by Terraria!
'''