modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
authors="Jack Gagnon" #optional

[[mods]] #mandatory
modId="aamod" #mandatory
version="0.0.1" #mandatory
displayName="Action-Adventure Mod" #mandatory
description='''
An Action Adventure Mod based on Terraria.
'''